apiVersion: v1
kind: Secret
metadata:
  name: bankapp-mysql-secret
  namespace: bankapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=           # Base64-encoded "Test@123"
  MYSQL_DATABASE: YmFua2FwcGRi                # Base64-encoded "bankappdb"
  SPRING_DATASOURCE_USERNAME: cm9vdA==        # Base64-encoded "root"
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjM=    # Base64-encoded "Test@123"
